package notifications

import (
	"testing"
	"time"

	gerrit "github.com/andygrunwald/go-gerrit"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func ts(t *testing.T, s string) gerrit.Timestamp {
	t.Helper()

	parsed, err := time.Parse(gerritTimeLayout, s)
	require.NoError(t, err)

	return gerrit.Timestamp{Time: parsed}
}

func account(id int, username string) gerrit.AccountInfo {
	return gerrit.AccountInfo{
		AccountID: id,
		Username:  username,
	}
}

// movedAt is the detailed-fetch updated timestamp every extraction case uses.
const movedAt = "2026-07-01 11:00:00.000000000"

// detailedChange builds the minimal detailed-fetch shape extraction reads.
func detailedChange(t *testing.T, status string) *gerrit.ChangeInfo {
	t.Helper()

	return &gerrit.ChangeInfo{
		Number:  123,
		Project: "core",
		Status:  status,
		Updated: ts(t, movedAt),
	}
}

func Test_ExtractDelta(t *testing.T) {
	t.Parallel()

	base := "2026-07-01 10:00:00.000000000"
	seed := func(t *testing.T) Cursor {
		t.Helper()

		return NewCursor(ts(t, base).Time, "NEW")
	}

	t.Run("quiet change yields an empty delta and only moves updated", func(t *testing.T) {
		t.Parallel()

		info := detailedChange(t, "NEW")

		delta, next := extractDelta(seed(t), info, nil)

		assert.True(t, delta.Empty())
		assert.Equal(t, info.Updated.Time, next.Updated)
		assert.Equal(t, seed(t).Messages, next.Messages)
	})

	t.Run("new messages extracted with marks advanced", func(t *testing.T) {
		t.Parallel()

		info := detailedChange(t, "NEW")

		info.Messages = []gerrit.ChangeMessageInfo{
			{ID: "m1", Author: account(8, "bob"), Date: ts(t, base), Message: "old news", Tag: "", RevisionNumber: 1},
			{
				ID: "m2", Author: account(8, "bob"), Date: ts(t, "2026-07-01 10:30:00.000000000"),
				Message: "fresh reply", Tag: "", RevisionNumber: 2,
			},
			{
				ID: "m3", Author: account(9, "ci"), Date: ts(t, "2026-07-01 11:00:00.000000000"),
				Message: "Build succeeded", Tag: "autogenerated:ci", RevisionNumber: 2,
			},
		}

		delta, next := extractDelta(seed(t), info, nil)

		require.Len(t, delta.Messages, 2, "message dated at the cursor is old news")
		assert.Equal(t, "m2", delta.Messages[0].ID)
		assert.Equal(t, "m3", delta.Messages[1].ID)
		assert.Equal(t, ts(t, "2026-07-01 11:00:00.000000000").Time, next.Messages)

		// Replay against the advanced cursor is silent.
		replay, _ := extractDelta(next, info, nil)
		assert.True(t, replay.Empty())
	})

	t.Run("vote-only update produces vote events", func(t *testing.T) {
		t.Parallel()

		info := detailedChange(t, "NEW")

		info.Labels = map[string]gerrit.LabelInfo{
			"Verified": {
				All: []gerrit.ApprovalInfo{
					{AccountInfo: account(9, "ci"), Value: 1, Date: "2026-07-01 11:00:00.000000000"},
				},
			},
			"Code-Review": {
				All: []gerrit.ApprovalInfo{
					{AccountInfo: account(8, "bob"), Value: 2, Date: "2026-07-01 10:45:00.000000000"},
					{AccountInfo: account(7, "alice"), Value: 0, Date: ""},
				},
			},
		}

		delta, next := extractDelta(seed(t), info, nil)

		require.Len(t, delta.Votes, 2, "a dateless reviewer entry never voted")
		assert.Equal(t, "Code-Review", delta.Votes[0].Label)
		assert.Equal(t, 2, delta.Votes[0].Value)
		assert.Equal(t, "bob", delta.Votes[0].Voter.Username)
		assert.Equal(t, "Verified", delta.Votes[1].Label)
		assert.Empty(t, delta.Messages)
		assert.Equal(t, ts(t, "2026-07-01 11:00:00.000000000").Time, next.Votes)

		replay, _ := extractDelta(next, info, nil)
		assert.True(t, replay.Empty())
	})

	t.Run("comment burst yields one delta with the full listing", func(t *testing.T) {
		t.Parallel()

		info := detailedChange(t, "NEW")
		old := ts(t, base)
		fresh1 := ts(t, "2026-07-01 10:50:00.000000000")
		fresh2 := ts(t, "2026-07-01 11:00:00.000000000")
		comments := map[string][]gerrit.CommentInfo{
			"main.go": {
				{ID: "c1", Updated: &old, Message: "seen before"},
				{ID: "c2", Updated: &fresh1, Message: "new root"},
				{ID: "c3", Updated: &fresh2, Message: "reply", InReplyTo: "c2"},
			},
		}

		delta, next := extractDelta(seed(t), info, comments)

		assert.Equal(t, map[string]bool{"c2": true, "c3": true}, delta.NewComments)
		assert.Equal(t, comments, delta.Comments, "renderer needs the surrounding threads, not only the new comments")
		assert.Equal(t, fresh2.Time, next.Comments)

		replay, _ := extractDelta(next, info, comments)
		assert.True(t, replay.Empty())
	})

	t.Run("status transition detected from the status field", func(t *testing.T) {
		t.Parallel()

		info := detailedChange(t, "MERGED")

		delta, next := extractDelta(seed(t), info, nil)

		require.NotNil(t, delta.Transition)
		assert.Equal(t, "NEW", delta.Transition.From)
		assert.Equal(t, "MERGED", delta.Transition.To)
		assert.Equal(t, "MERGED", next.Status)

		replay, _ := extractDelta(next, info, nil)
		assert.True(t, replay.Empty())
	})

	t.Run("mixed activity groups into one delta", func(t *testing.T) {
		t.Parallel()

		fresh := ts(t, "2026-07-01 11:00:00.000000000")

		info := detailedChange(t, "MERGED")

		info.Messages = []gerrit.ChangeMessageInfo{
			{ID: "m1", Author: account(8, "bob"), Date: fresh, Message: "merged", Tag: "", RevisionNumber: 2},
		}
		info.Labels = map[string]gerrit.LabelInfo{
			"Code-Review": {
				All: []gerrit.ApprovalInfo{
					{AccountInfo: account(8, "bob"), Value: 2, Date: "2026-07-01 11:00:00.000000000"},
				},
			},
		}

		comments := map[string][]gerrit.CommentInfo{
			"main.go": {{ID: "c1", Updated: &fresh, Message: "nice"}},
		}

		delta, next := extractDelta(seed(t), info, comments)

		assert.Len(t, delta.Messages, 1)
		assert.Len(t, delta.Votes, 1)
		assert.Len(t, delta.NewComments, 1)
		require.NotNil(t, delta.Transition)
		assert.False(t, delta.Empty())

		replay, _ := extractDelta(next, info, comments)
		assert.True(t, replay.Empty())
	})
}
