package tools_test

import (
	"net/http"
	"regexp"
	"strings"
	"testing"
	"time"

	gerrit "github.com/andygrunwald/go-gerrit"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"dev.gaijin.team/go/go-gerrit-mcp/internal/notifications"
	"dev.gaijin.team/go/go-gerrit-mcp/internal/tools"
)

func gerritTS(t *testing.T, s string) gerrit.Timestamp {
	t.Helper()

	parsed, err := time.Parse("2006-01-02 15:04:05.000000000", s)
	require.NoError(t, err)

	return gerrit.Timestamp{Time: parsed}
}

func activityChange(t *testing.T) *gerrit.ChangeInfo {
	t.Helper()

	return &gerrit.ChangeInfo{
		Number:  123,
		Project: "core",
		Status:  "NEW",
		Updated: gerritTS(t, "2026-07-02 11:30:00.000000000"),
	}
}

func emptyDelta(t *testing.T) *notifications.Delta {
	t.Helper()

	return &notifications.Delta{
		Change:      activityChange(t),
		Messages:    nil,
		Votes:       nil,
		Comments:    nil,
		NewComments: nil,
		Transition:  nil,
	}
}

// activityComments is the published comment listing shared by the thread
// rendering tests and the byte-identity probe: one two-comment unresolved
// thread on main.go where only the reply is new, plus an old resolved
// thread on util.go that no new comment touches.
func activityComments(t *testing.T) map[string][]gerrit.CommentInfo {
	t.Helper()

	rootAt := gerritTS(t, "2026-07-01 10:00:00.000000000")
	replyAt := gerritTS(t, "2026-07-02 11:30:00.000000000")
	oldAt := gerritTS(t, "2026-06-30 09:00:00.000000000")
	unresolved := true
	resolved := false

	return map[string][]gerrit.CommentInfo{
		"main.go": {
			{
				ID: "c1", PatchSet: 1, Line: 3, Message: "nil deref here",
				Updated: &rootAt, Author: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Unresolved: &unresolved,
			},
			{
				ID: "c2", PatchSet: 1, Line: 3, InReplyTo: "c1", Message: "fixed in ps2",
				Updated: &replyAt, Author: gerrit.AccountInfo{Name: "Alice", Username: "alice"},
				Unresolved: &unresolved,
			},
		},
		"util.go": {
			{
				ID: "c9", PatchSet: 1, Line: 8, Message: "nit: rename",
				Updated: &oldAt, Author: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Unresolved: &resolved,
			},
		},
	}
}

func Test_DeltaRenderer(t *testing.T) {
	t.Parallel()

	renderer := tools.NewDeltaRenderer()

	t.Run("messages", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Messages = []gerrit.ChangeMessageInfo{
			{
				ID: "m1", Author: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Date: gerritTS(t, "2026-07-02 11:00:00.000000000"), Message: "Looks good to me",
				Tag: "", RevisionNumber: 2,
			},
			{
				ID: "m2", Author: gerrit.AccountInfo{Name: "CI", Username: "ci"},
				Date: gerritTS(t, "2026-07-02 11:30:00.000000000"), Message: "Build succeeded",
				Tag: "autogenerated:ci", RevisionNumber: 2,
			},
		}

		content, meta := renderer.Render(d)

		golden(t, "render-activity-messages", content)
		assert.Equal(t, map[string]string{"change": "123", "project": "core", "kind": "message"}, meta)
	})

	t.Run("votes", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Votes = []notifications.Vote{
			{
				Label: "Code-Review", Value: 2,
				Voter: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Date:  gerritTS(t, "2026-07-02 11:30:00.000000000").Time,
			},
			{
				Label: "Verified", Value: -1,
				Voter: gerrit.AccountInfo{Name: "CI", Username: "ci"},
				Date:  gerritTS(t, "2026-07-02 11:29:00.000000000").Time,
			},
		}

		content, meta := renderer.Render(d)

		golden(t, "render-activity-votes", content)
		assert.Equal(t, "vote", meta["kind"])
	})

	t.Run("threads carry only touched threads", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Comments = activityComments(t)
		d.NewComments = map[string]bool{"c2": true}

		content, meta := renderer.Render(d)

		golden(t, "render-activity-threads", content)
		assert.Equal(t, "comment", meta["kind"])
		assert.NotContains(t, content, "util.go", "untouched threads must not render")
		assert.Contains(t, content, "nil deref here", "the touched thread arrives whole, not only its new comment")
	})

	t.Run("transition", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Change.Status = "ABANDONED"
		d.Transition = &notifications.Transition{From: "NEW", To: "ABANDONED"}

		content, meta := renderer.Render(d)

		golden(t, "render-activity-transition", content)
		assert.Equal(t, "transition", meta["kind"])
	})

	t.Run("mixed delta renders every kind in one payload", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Change.Status = "MERGED"
		d.Messages = []gerrit.ChangeMessageInfo{
			{
				ID: "m1", Author: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Date: gerritTS(t, "2026-07-02 11:30:00.000000000"), Message: "Change has been merged",
				Tag: "", RevisionNumber: 2,
			},
		}
		d.Votes = []notifications.Vote{
			{
				Label: "Code-Review", Value: 2,
				Voter: gerrit.AccountInfo{Name: "Bob", Username: "bob"},
				Date:  gerritTS(t, "2026-07-02 11:29:00.000000000").Time,
			},
		}
		d.Comments = activityComments(t)
		d.NewComments = map[string]bool{"c2": true}
		d.Transition = &notifications.Transition{From: "NEW", To: "MERGED"}

		content, meta := renderer.Render(d)

		golden(t, "render-activity-mixed", content)
		assert.Equal(t, map[string]string{
			"change": "123", "project": "core", "kind": "message,vote,comment,transition",
		}, meta)
	})

	t.Run("meta keys satisfy the channel identifier restriction", func(t *testing.T) {
		t.Parallel()

		d := emptyDelta(t)

		d.Transition = &notifications.Transition{From: "NEW", To: "MERGED"}

		_, meta := renderer.Render(d)

		key := regexp.MustCompile(`^[A-Za-z0-9_]+$`)
		for k := range meta {
			assert.True(t, key.MatchString(k), "meta key %q would be dropped by the client", k)
		}
	})
}

// Test_DeltaRenderer_ThreadParity proves payload thread rendering is
// byte-identical to get_change_comments rendering the same comments: the
// thread block of the tool output must appear verbatim in the payload.
func Test_DeltaRenderer_ThreadParity(t *testing.T) {
	t.Parallel()

	commentsJSON := ")]}'\n" + `{
  "main.go": [
    {"id": "c1", "patch_set": 1, "line": 3, "message": "nil deref here",
     "updated": "2026-07-01 10:00:00.000000000",
     "author": {"name": "Bob", "username": "bob"}, "unresolved": true},
    {"id": "c2", "patch_set": 1, "line": 3, "in_reply_to": "c1", "message": "fixed in ps2",
     "updated": "2026-07-02 11:30:00.000000000",
     "author": {"name": "Alice", "username": "alice"}, "unresolved": true}
  ]
}`

	cs := session(t, func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/a/accounts/self":
			_, _ = w.Write([]byte(selfJSON))
		case strings.HasSuffix(r.URL.Path, "/drafts"):
			_, _ = w.Write([]byte(")]}'\n{}"))
		default:
			_, _ = w.Write([]byte(commentsJSON))
		}
	})

	res, err := cs.CallTool(t.Context(), &mcp.CallToolParams{
		Name:      "get_change_comments",
		Arguments: map[string]any{"change": "123"},
	})
	require.NoError(t, err)
	require.False(t, res.IsError)

	toolText, ok := res.Content[0].(*mcp.TextContent)
	require.True(t, ok)

	start := strings.Index(toolText.Text, "<thread")
	end := strings.LastIndex(toolText.Text, "</thread>") + len("</thread>")

	require.Positive(t, start)

	toolThread := toolText.Text[start:end]

	d := emptyDelta(t)

	d.Comments = map[string][]gerrit.CommentInfo{"main.go": activityComments(t)["main.go"]}
	d.NewComments = map[string]bool{"c2": true}

	content, _ := tools.NewDeltaRenderer().Render(d)

	assert.Contains(t, content, toolThread,
		"payload thread rendering must be byte-identical to the comments tool")
}
